// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Xkz95z-hRSMszA4VUi8mLARpd7QdVFc',
    appId: '1:54492635153:web:152135ec631e13fa8c51b0',
    messagingSenderId: '54492635153',
    projectId: 'kicaw-smart-room',
    authDomain: 'kicaw-smart-room.firebaseapp.com',
    databaseURL: 'https://kicaw-smart-room-default-rtdb.firebaseio.com',
    storageBucket: 'kicaw-smart-room.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh6T6BfKPQN06R-ei4QwN2_8iSvRgKyRg',
    appId: '1:54492635153:android:a94a5965c88c09dc8c51b0',
    messagingSenderId: '54492635153',
    projectId: 'kicaw-smart-room',
    databaseURL: 'https://kicaw-smart-room-default-rtdb.firebaseio.com',
    storageBucket: 'kicaw-smart-room.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Xkz95z-hRSMszA4VUi8mLARpd7QdVFc',
    appId: '1:54492635153:web:aa2009de8d2d14b68c51b0',
    messagingSenderId: '54492635153',
    projectId: 'kicaw-smart-room',
    authDomain: 'kicaw-smart-room.firebaseapp.com',
    databaseURL: 'https://kicaw-smart-room-default-rtdb.firebaseio.com',
    storageBucket: 'kicaw-smart-room.firebasestorage.app',
  );
}
